### ISSUE TITLE
JavaScript coding style and linting

### ISSUE THREAD

**Issue by jsidd** [mattlee2021/spaceX_Launches_React#3]
I started reviewing the codebase and noticed that the use of semicolons is inconsistent between files, and more concerning within one file. 

As an improvement, you can introduce automatic linting.

The easiest would to be to introduce a popular coding style so you do not have to create special rules yourself.

I recommend this style as it enforces no semicolons:
https://github.com/standard/standard

**Comment by mattlee2021** [comment]
Refactored code according to JS Standard by installing the relevant extension into VS Code.
